[package]
name = "spartan"
version = "0.0.0"
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>"]
edition = "2018"

[dependencies]
rug = "1.12.0"

[dependencies.rayon]
optional = true
version = "1.5.0"

[dev-dependencies]
rand = "0.8.3"

[features]
default = ["parallel"]
parallel = ["rayon"]
