[package]
name = "spartan"
version = "0.0.0"
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>"]
edition = "2018"

[dependencies]
rayon = "1.3.0"
rug = "1.11.0"

[dev-dependencies]
rand = "0.8.1"
#ring = "0.16.19"
